export interface Dinner {
  dish: string;
  meat: string;
}

export const dinners: Dinner[] = [
  { dish: "Svin med frosne grønnsaker", meat: "svin" },
  { dish: "Kyllingsalat", meat: "kylling" },
  { dish: "Taco", meat: "storfe" },
  { dish: "Lasagne (suppe)", meat: "storfe" },
  { dish: "Pokebowl", meat: "fisk" },
  { dish: "Kyllingkjøttboller", meat: "kylling" },
  { dish: "Tortellini med kylling", meat: "kylling" },
  { dish: "Fiskesuppe", meat: "fisk" },
  { dish: "Laksewok", meat: "fisk" },
  { dish: "Pizza", meat: "vegetar" },
  { dish: "Søtpotetsalat med kylling", meat: "kylling" },
  { dish: "Bretagnegryte", meat: "kylling" },
  { dish: "Pasta med tomatsaus", meat: "vegetar" },
  { dish: "Shakshuka", meat: "vegetar" },
  { dish: "Wrap med halloumi", meat: "vegetar" },
  { dish: "Sommerruller", meat: "vegetar" },
  {
    dish: "Pasta med kylling og salat og pesto calabrese",
    meat: "kylling",
  },
  { dish: "Kylling fajitas", meat: "kylling" },
  { dish: "Pulled kylling", meat: "kylling" },
  { dish: "Butter chicken med ris og grønnsaker", meat: "kylling" },
  { dish: "Nachos", meat: "storfe" },
  { dish: "Pølsegryte", meat: "svin" },
  { dish: "Laks teriyaki", meat: "fisk" },
  { dish: "Scampi med pasta og creme fraiche", meat: "skalldyr" },
  { dish: "Ovnsbakt laks med grønnsaker", meat: "fisk" },
  { dish: "Burger", meat: "storfe" },
  { dish: "Fiskeburger med mangochutney", meat: "fisk" },
  { dish: "Halloumi burger", meat: "vegetar" },
  { dish: "Chili con carne", meat: "storfe" },
  { dish: "Sloppy joes", meat: "storfe" },
  { dish: "Stekt ris med grønnsaker", meat: "vegetar" },
  { dish: "Pannekaker", meat: "vegetar" },
  { dish: "Laksewrap", meat: "fisk" },
  { dish: "Szechuan", meat: "storfe" },
  { dish: "Pasta carbonara", meat: "svin" },
  { dish: "Bali kyllinggryte", meat: "kylling" },
  { dish: "Moussaka", meat: "storfe" },
  { dish: "Tikka masala", meat: "kylling" },
  { dish: "Mac n cheese", meat: "vegetar" },
  { dish: "Risengrynsgrøt", meat: "vegetar" },
  { dish: "Hjemmelaga tomatsuppe", meat: "vegetar" },
  {
    dish: "Kylling ris, grønnsaker og sweet and sour saus",
    meat: "kylling",
  },
  { dish: "Kylling tandoori", meat: "kylling" },
  { dish: "Søtpotetnachos", meat: "vegetar" },
];
